# Use OpenJDK 17 as base image
FROM openjdk:17-jdk-slim

# Set working directory
WORKDIR /app

# Copy the pre-built JAR file from your local `build/libs` directory into the container
# The JAR file is renamed to app.jar for a consistent entrypoint
COPY build/libs/expt-0.0.1-SNAPSHOT.jar app.jar

# Expose port 8080 for the application
EXPOSE 8080

# Run the application
CMD ["java", "-jar", "app.jar"]
